### ISSUE TITLE
ValueError: Nope this is an empty list...

### ISSUE THREAD

**Issue by spookyahell** [hyugogirubato/DVDFabExtendDownload#1]
````C:\Users\1234\Downloads>dvdfab.py
[I] DVDFab ExtendDownload v1.0.0
[I] Product: Geekit
[I] Platform: win
[I] Software: Geekit
Traceback (most recent call last):
  File "C:\Users\1234\Downloads\dvdfab.py", line 154, in <module>
    version, index = pick([v['version'] for v in versions], 'Version')
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\1234\AppData\Local\Programs\Python\Python312\Lib\site-packages\pick\__init__.py", line 236, in pick
    picker: Picker = Picker(
                     ^^^^^^^
  File "<string>", line 13, in __init__
  File "C:\Users\1234\AppData\Local\Programs\Python\Python312\Lib\site-packages\pick\__init__.py", line 45, in __post_init__
    raise ValueError("options should not be an empty list")
ValueError: options should not be an empty list
````

uhm...

**Comment by hyugogirubato** [comment]
Thank you for this feedback, I just fixed the problem!
